<a href="https://colab.research.google.com/github/keliwu5/ML100Days/blob/main/homework/%E4%BD%9C%E6%A5%AD%E9%A1%8C%E7%9B%AE_D07.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

作業目標<br>
活用矩陣運算，實做線性代數<br>
作業重點<br>
線性代數公式應用<br>
矩陣相乘維度需要對好，例如:2X3矩陣乘上3X5矩陣得到2X5矩陣

題目:<br>
array1 = np.array([[10, 8], [3, 5]]) <br>
1. 運用上列array計算反矩陣，乘上原矩陣，並觀察是否為單位矩陣?
2. 運用上列array計算特徵值、特徵向量?
3. 運用上列array計算SVD?

In [1]:
import numpy as np

In [2]:
#1. 運用上列array計算反矩陣，乘上原矩陣，並觀察是否為單位矩陣?
array1 = np.array([[10, 8], [3, 5]])

In [3]:
#反矩陣
inv_array1 = np.linalg.inv(array1)

In [7]:
np.dot(inv_array1, array1)

array([[ 1.00000000e+00, -5.55111512e-17],
       [-1.11022302e-16,  1.00000000e+00]])

In [8]:
#2. 運用上列array計算特徵值、特徵向量?
w, v = np.linalg.eig(array1)

In [11]:
w

array([13.,  2.])

In [10]:
v

array([[ 0.93632918, -0.70710678],
       [ 0.35112344,  0.70710678]])

In [12]:
#3. 運用上列array計算SVD?
u, s, vh = np.linalg.svd(array1)

In [13]:
u

array([[-0.91663818, -0.39971796],
       [-0.39971796,  0.91663818]])

In [14]:
s

array([13.94721714,  1.86417116])

In [15]:
vh

array([[-0.74319741, -0.6690722 ],
       [-0.6690722 ,  0.74319741]])