<a href="https://colab.research.google.com/github/keliwu5/ML100Days/blob/main/homework/%E4%BD%9C%E6%A5%AD_D06.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

作業目標<br>
讀取存取陣列資料<br>
作業重點<br>
多陣列存一起需要存成npz，讀取須注意npz中有多個陣列

題目:<br>
1. 將下兩列array存成npz檔<br>
array1 = np.array(range(30))<br>
array2 = np.array([2,3,5])<br>
2. 讀取剛剛的npz檔，加入下列array一起存成新的npz檔


In [2]:
import numpy as np

In [3]:
#. 將下兩列array存成npz檔
array1 = np.array(range(30))
array2 = np.array([2,3,5])
with open('npzarray.npz', 'wb') as f:
  np.savez(f, array1 = array1, array2 = array2)


In [ ]:
#2. 讀取剛剛的npz檔，加入下列array一起存成新的npz檔

In [130]:
npzfile = np.load('npzarray.npz')

In [131]:
a = npzfile['array1']

In [132]:
b = npzfile['array2']

In [133]:
npzfile = np.load('multi_array.npz')

In [134]:
c = npzfile['array1']

In [136]:
d = npzfile['array2']

In [168]:
e = npzfile['array3']

In [167]:
f = np.genfromtxt('names.txt', dtype= str, delimiter=',')

In [206]:
g = np.load('npzarray.npz')['array1']

In [207]:
h = np.load('npzarray.npz')['array2']

In [208]:
i = np.load('one_array.npy')

In [209]:
j = np.loadtxt('test',delimiter=',')

In [210]:
k = np.genfromtxt('test.csv',delimiter=',')

In [211]:
l = np.load('test.npy')

In [212]:
m = np.genfromtxt('test.out', delimiter=',', comments='#')

In [213]:
n = np.genfromtxt('transform.txt', delimiter=',', dtype="i8,i8,U3,U3")

In [222]:
with open('array_sum.npz', 'wb') as z:
  np.savez(z, array1 = a, array2 = b, array3 = c, array4 = d, array5 = e, array6 = f, array7 = g, array8 = h, array9 = i, array10 = j, array11 = k, array12 = l, array13 = m, array14 = n)

In [223]:
npz_sum = np.load('array_sum.npz')

In [224]:
npz_sum.files

['array1',
 'array2',
 'array3',
 'array4',
 'array5',
 'array6',
 'array7',
 'array8',
 'array9',
 'array10',
 'array11',
 'array12',
 'array13',
 'array14']

In [225]:
for i in range(len(npz_sum)):
  print(npz_sum['array'+str(i+1)])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
[2 3 5]
[0 1 2 3 4 5 6 7 8 9]
[1 2 3]
[0.5788873  0.69082947 0.04922545 0.86517602 0.29889969 0.55285575
 0.69389689 0.49183867 0.8308363  0.06454569]
[['a' 'b' 'c']
 ['1' '2' '3']
 ['4' '5' '6']
 ['7' '8' '9']]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
[2 3 5]
13
[0. 1. 2. 3. 4.]
[[0. 1. 2. 3. 4.]
 [5. 6. 7. 8. 9.]]
[1 2]
[0. 1. 2. 3. 4.]
[(1, 2, 'Yes', '87%') (3, 4, 'No', '3%') (5, 6, 'Yes', '55%')]
