<a href="https://colab.research.google.com/github/keliwu5/ML100Days/blob/main/homework/%E4%BD%9C%E6%A5%AD%E9%A1%8C%E7%9B%AE_D05.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

作業目標<br>
計算有缺失值的資料，統計量實作<br>
作業重點<br>
當遇到缺失值有函式可以處理，不須額外寫程式刪除<br>
計算統計量時不能出現缺失值

題目:<br>
english_score = np.array([55,89,76,65,48,70])<br>
math_score = np.array([60,85,60,68,np.nan,60])<br>
chinese_score = np.array([65,90,82,72,66,77])<br>
上3列共六位同學的英文、數學、國文成績，第一個元素代表第一位同學，舉例第一位同學英文55分、數學60分、國文65分，今天第五位同學因某原因沒來考試，導致數學成績缺值，運用上列數據回答下列問題。<br>
1. 請計算各科成績平均、最大值、最小值、標準差，其中數學缺一筆資料可忽略?
2. 第五位同學補考數學後成績為55，請計算補考後數學成績平均、最大值、最小值、標準差?
3. 用補考後資料找出與國文成績相關係數最高的學科?

In [1]:
import numpy as np

In [2]:
english_score = np.array([55,89,76,65,48,70])
math_score = np.array([60,85,60,68,np.nan,60])
chinese_score = np.array([65,90,82,72,66,77])

In [3]:
subject = [english_score, math_score, chinese_score]

In [4]:
math_score

array([60., 85., 60., 68., nan, 60.])

In [5]:
#1. 請計算各科成績平均、最大值、最小值、標準差，其中數學缺一筆資料可忽略?
for i in range(len(subject)):
  if i == 0:
    sub_name = 'english'
  elif i == 1:
    sub_name = 'math'
  else:
    sub_name = 'chinese'
  print(sub_name+'_mean : '+str(np.nanmean(subject[i])))
  print(sub_name+'_max : '+str(np.nanmax(subject[i])))
  print(sub_name+'_min : '+str(np.nanmin(subject[i])))
  print(sub_name+'_std : '+str(np.nanstd(subject[i])))


english_mean : 67.16666666666667
english_max : 89
english_min : 48
english_std : 13.433995020924426
math_mean : 66.6
math_max : 85.0
math_min : 60.0
math_std : 9.707728879609279
chinese_mean : 75.33333333333333
chinese_max : 90
chinese_min : 65
chinese_std : 8.825468196582484


In [6]:
math_score[4]=55

In [7]:
math_score

array([60., 85., 60., 68., 55., 60.])

In [8]:
#2. 第五位同學補考數學後成績為55，請計算補考後數學成績平均、最大值、最小值、標準差?
print('math_mean : '+str(np.mean(subject[1])))
print('math_max : '+str(np.nanmax(subject[1])))
print('math_min : '+str(np.nanmin(subject[1])))
print('math_std : '+str(np.nanstd(subject[1])))

math_mean : 64.66666666666667
math_max : 85.0
math_min : 55.0
math_std : 9.860132971832694


In [ ]:
#3. 用補考後資料找出與國文成績相關係數最高的學科?

In [13]:
np.corrcoef(chinese_score, math_score)

array([[1.        , 0.74056803],
       [0.74056803, 1.        ]])

In [11]:
np.corrcoef(chinese_score, english_score)

array([[1.        , 0.97792828],
       [0.97792828, 1.        ]])